org.gradle.jvmargs=-Xmx3G
org.gradle.debug=false
parchment_minecraft_version=1.21.8
parchment_mappings_version=2025.09.14
minecraft_version=1.21.8
minecraft_version_range=>=1.21.6 <=1.21.8
fabric_loader_version=0.18.3
fabric_api_version=0.136.1+1.21.8


mod_id=parcool
mod_name=ParCool!
mod_license=LGPL-3.0
# Version Format (McVersion-MajorMOD.MajorAPI.Minor.Patch)
mod_version=3.4.3.2
patchouli_version=1.21-88-FABRIC
forgeconfigapiport_version = 21.8.2